[colors.primary]
background = '#f4f4f7'
foreground = '#080B11'

[colors.cursor]
text = '#f4f4f7'
cursor = '#080B11'

[colors.normal]
black = '#f4f4f7'
red = '#104390'
green = '#123ea6'
yellow = '#e26e19'
blue = '#1351ac'
magenta = '#1761cf'
cyan = '#387de8'
white = '#080B11'

[colors.bright]
black = '#6d7079'
red = '#104390'
green = '#123ea6'
yellow = '#e26e19'
blue = '#1351ac'
magenta = '#1761cf'
cyan = '#387de8'
white = '#080B11'
