#!/bin/sh
alias fucking="sudo"                                                            # Because sometimes I'm frustrated
alias cp='cp -ivR'                                                              # Prompt if overwrite, verbose
alias grep='grep --color=auto'
alias mv='mv -iv'                                                               # Prompt if overwrite, verbose
alias lynx='lynx -vikeys'
alias mkdir='mkdir -pv'                                                         # Create intermediate dirs, verbose
alias ls="command ls -lh"                                                       # List in long format, human-readable sizes
alias l="command ls -lah"                                                       # Ls but with all files
alias ll="command ls -FGlAhpO@"                                                 # Ls but show everything you can
alias l.="command ls -a | grep '^\.'"                                           # Ls but only dotfiles
alias less='less -iRXc'                                                         # Search ig case, fix ANSI colors, don't send init strings, clear screen
alias du="du -skh"                                                              # Show entry for each file, show block counts in 1kb blocks, human-readable sizes
alias df="df -h"                                                                # Show human-readable sizes
alias bc="bc -ql"                                                               # Don't print welcome message, use the standard math lib
alias jobs="jobs -l"                                                            # Show everything including PIDs
alias htop='sudo htop'                                                          # Run htop as root by default
alias g='git'                                                                   # Make git easier to type
alias wheredef='type -a'                                                        # Where is a function defined?
alias j='joplin'
alias tree="tree -CAFa -I 'CVS|*.*.package|.svn|.git|node_modules' --dirsfirst" # Colorize, ANSI graphics hack, indicate ft with appendices, print all files, ignore certain patterns, list dirs first
alias lsblk="lsblk -o NAME,LABEL,PARTLABEL,TYPE,FSTYPE,SIZE,MOUNTPOINT,STATE"   # The columns I want to see in lsblk
alias confucius="curl confucius-quote.herokuapp.com"                            # A joke curl service I made
alias tx="tmuxinator"
alias mpva="mpv --no-audio-display --no-video --volume=50"
alias irrsi="irssi --home=~/.config/irssi"
alias scim="sc-im"
alias mbsync='mbsync -c $HOME/.config/mbsync/mbsyncrc'
alias mutt='BW_SESSION="$(bw unlock --raw)" neomutt'
[ -n "$VIM_TERMINAL" ] && alias vim=vimsend
{ [ -f ~/.config/dark-theme ] && alias bat="bat --theme=1337"; } || alias bat="bat --theme=GitHub"
