#!/bin/sh
[ -x /usr/libexec/path_helper ] && unset PATH && eval "$(/usr/libexec/path_helper -s)"
[ -d "$HOME/bin" -o -L "$HOME/bin" ]                                                             && [ -n "${PATH##*"$HOME/bin"*}" ]                               && PATH="$HOME/bin:$PATH"
[ -d "$HOME/.local/bin" -o -L "$HOME/.local/bin" ]                                               && [ -n "${PATH##*"$HOME/.local/bin"*}" ]                        && PATH="$HOME/.local/bin:$PATH"
[ -d "$HOME/.scripts" -o -L "$HOME/.scripts" ]                                                   && [ -n "${PATH##*"$HOME/.scripts"*}" ]                          && PATH="$HOME/.scripts:$PATH"
[ -d "$HOME/.bin" -o -L "$HOME/.bin" ]                                                           && [ -n "${PATH##*"$HOME/.bin"*}" ]                              && PATH="$HOME/.bin:$PATH"
[ -d "$HOME/go/bin" -o -L "$HOME/go/bin" ]                                                       && [ -n "${PATH##*"$HOME/go/bin"*}" ]                            && PATH="$HOME/go/bin:$PATH"
[ -d "/usr/local/opt/util-linux/bin" -o -L "/usr/local/opt/util-linux/bin" ]                     && [ -n "${PATH##*"/usr/local/opt/util-linux/bin"*}" ]           && PATH="/usr/local/opt/util-linux/bin:$PATH"
[ -d "$HOME/.config/.ghcup/bin" -o -L "$HOME/.config/.ghcup/bin" ]                               && [ -n "${PATH##*"$HOME/.config/.ghcup/bin"*}" ]                && PATH="$HOME/.config/.ghcup/bin:$PATH"
[ -d "/usr/local/sbin" -o -L "/usr/local/sbin" ]                                                 && [ -n "${PATH##*"/usr/local/sbin"*}" ]                         && PATH="/usr/local/sbin:$PATH"
[ -d "$HOME/.bin" -o -L "$HOME/.bin" ]                                                           && [ -n "${PATH##*"$HOME/.bin"*}" ]                              && PATH="$HOME/.bin:$PATH"
[ -d "/usr/local/opt/coreutils/libexec/gnubin" -o -L "/usr/local/opt/coreutils/libexec/gnubin" ] && [ -n "${PATH##*"/usr/local/opt/coreutils/libexec/gnubin"*}" ] && PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
[ -d "$HOME/.local/gnat/bin" -o -L "$HOME/.local/gnat/bin" ]                                     && [ -n "${PATH##*"$HOME/.local/gnat/bin"*}" ]                   && PATH="$HOME/.local/gnat/bin:$PATH"
export PATH
