#!/bin/sh
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# System-wide .profile for sh(1)
if [ -x /usr/libexec/path_helper ]; then
  eval "$(/usr/libexec/path_helper -s)"
fi

if [ "${BASH-no}" != "no" ]; then
    [ -r /etc/bashrc ] && . /etc/bashrc
fi

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
if [ -d "$HOME/.scripts" ] ; then
    PATH="$HOME/.scripts:$PATH"
fi
if [ -d "$HOME/.bin" ] ; then
    PATH="$HOME/.bin:$PATH"
fi
if [ -d "$HOME/go/bin" ] ; then
    PATH="$HOME/go/bin:$PATH"
fi
if [ -f "$HOME/.secret_env_variables" ] ; then
  . "$HOME/.secret_env_variables"
fi
# Haskell
if [ -d "$HOME/.ghcup/bin" ]; then
   PATH="$HOME/.ghcup/bin:$PATH"
fi
if [ -d "/usr/local/sbin" ]; then
  PATH="/usr/local/sbin:$PATH"
fi
if command -v rbenv 1>/dev/null 2>&1; then
  eval "$(rbenv init -)"
fi
if [ -d "/usr/local/opt/gnu-sed/libexec/gnubin" ]; then
  PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
fi
if [ -d "$HOME/.local/gnat/bin" ]; then
  PATH="$PATH:$HOME/.local/gnat/bin"
fi

export DOTFILES="$HOME/.dotfiles"
EDITOR="$(command -v vim)"; export EDITOR
export MUSIC_DIR="/Volumes/HDD/Music/iTunes/iTunes Media/Music"
if command -v bat 1>/dev/null 2>&1; then
  export PAGER="bat"
else
  export PAGER="less -R"
fi
export LC_NUMERIC=en_US.UTF-8
export LC_TIME=en_US.UTF-8
export LC_COLLATE=en_US.UTF-8
export LC_MONETARY=en_US.UTF-8
export LC_MESSAGES=en_US.UTF-8

source "$DOTFILES/shell/use-config-dir"
