#!/bin/sh
# shellcheck disable=SC2016
[ -n "$DOTFILES" ] || { printf '$DOTFILES not set, press enter to quit' && read -r && exit 1; }

source_if_exists() { [ -f "$1" ] && . "$1"; }

# Enable virtualenvwrapper if installed
if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
  export WORKON_HOME=$HOME/.config/virtualenvs
  VIRTUALENVWRAPPER_PYTHON=$(which python3); export VIRTUALENVWRAPPER_PYTHON
  export VIRTUALENVWRAPPER_SCRIPT=/usr/local/bin/virtualenvwrapper.sh
  mkdir -p "$WORKON_HOME"
  . /usr/local/bin/virtualenvwrapper_lazy.sh
fi

(cat ~/.cache/wal/sequences &)
. ~/.cache/wal/colors-tty.sh

# The 'z' command to jump around dirs
source_if_exists "$DOTFILES"/shell/z/z.sh

# Enable custom aliases and functions
source_if_exists "$DOTFILES/shell/aliases"
source_if_exists "$DOTFILES/shell/functions"
source_if_exists "$DOTFILES/shell/secret_env"
