#!/usr/bin/env zsh
# ZSH config {{{
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Aliases
source $HOME/.commonprofile

# Z initialization
if ! command -v z &> /dev/null; then
  . $DOTFILES/shell/z/z.sh
fi

# rbenv init
if [[ $PATH != *"$HOME/.rbenv/shims"* ]] && command -v rbenv &> /dev/null; then
  eval "$(rbenv init -)"
fi

# jenv
if command -v jenv &> /dev/null; then
  if [[ $PATH != *"$HOME/.jenv/bin"* ]]; then
    export PATH="$HOME/.jenv/bin:$PATH"
  fi
  eval "$(jenv init -)"
  export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home"
fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Keybinds
insert-arg-of-prev-cmd() {
: ${NUMERIC:-1}
(( NUMERIC++ ))
words=($(fc -ln -1))
RBUFFER+="$words[$NUMERIC] "
zle end-of-line
}

zle -N insert-arg-of-prev-cmd
bindkey "\e^y" insert-arg-of-prev-cmd

# readline-style line commenting
bindkey '\e#' pound-insert

# readline-style searching
bindkey '^]' vi-find-next-char
bindkey '^\e]' vi-find-prev-char

# Use lf to switch directories and bind it to ctrl-o
lfcd () {
  if ! command -v lf &>/dev/null; then echo "lf not installed." && return; fi
  tmp="$(mktemp)"
  lf -last-dir-path="$tmp" "$@"
  if [ -f "$tmp" ]; then
    dir="$(cat "$tmp")"
    rm -f "$tmp"
    [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
  fi
}
bindkey -s '^o' 'lfcd\n'
# }}}
# oh-my-zsh {{{
# Path to your oh-my-zsh installation.
export ZSH="$HOME"/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  sudo
  zsh-syntax-highlighting
)

#POWERLEVEL9K
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir virtualenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history ram time battery)

source $ZSH/oh-my-zsh.sh
# }}}
# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# vim: foldmethod=marker foldlevel=0
