#!/bin/bash

# Initial config, setting $radios and $radio_names
if [ -e ~/.radio-config ]; then
    source ~/.radio-config
elif [ -e ~/.config/radio-config ]; then
    source ~/.config/radio-config
else
    echo "No radios set up. Please create a config file."
    exit 1
fi

## MAIN SCRIPT ##

VISUALISER=true
while getopts ":n" opt; do
  case ${opt} in
    n )
        VISUALISER=false      
  esac
done

clear
echo "Welcome to the command line radio player."
PS3="Select a radio, or type q to exit: "
select RADIO in "${radio_names[@]}"
do
	if [[ $RADIO = "q" ]]; then
		break
	else
		for i in "${!radio_names[@]}"; do
			if [[ "${radio_names[$i]}" = "${RADIO}" ]]; then
				clear
				echo "Now playing $RADIO"
                                echo "Loading..."
                                if $VISUALISER; then
                                    nice -n 20 mpv ${radios[$i]} --script="/Users/alex/.config/mpv/visualizer.lua" --really-quiet -vo caca
                                else
                                    nice -n 20 mpv ${radios[$i]}
                                fi
				break
			fi
		done
		break
	fi
done
