#!/bin/sh
# Wrapper script for `curl cheat.sh`, also sets colors depending on system theme
if ! command -v curl 1>/dev/null 2>&1; then
  echo "curl not installed." >&2
  exit 1
fi

! [ $# -ge 1 ] && echo "Argument required." && exit 1
if [ -f ~/.config/dark-theme ]; then query=''
else query='?style=trac'; fi
curl -Ls cheat.sh/"$1$query" | less -iR
