#!/bin/sh
# Script that crawls a URL and checks broken links
set -x
if ! command -v wget 1>/dev/null 2>&1; then
  echo "Please install wget."
  exit 1
elif [ $# -ne 2 ]; then
  echo "Usage:"
  echo "checklinks [URL] [LOGFILE]"
  exit 1
fi

# params: LOGFILE, URL
wget_with_flags() { wget --spider --recursive --no-directories --no-verbose --page-requisites --level inf --wait 2 -e robots=off -o "$2" "$1"; }
# flags=(--spider --recursive --no-directories --no-verbose --page-requisites --level inf -e robots=off)

wget_with_flags "$2" "$1"

grep -B 1 'broken link!' "$2" | less
