#!/bin/bash
die() {
  echo "$1" >&2
  exit 1
}
[ -z "$DOTFILES" ] && die '$DOTFILES variable not set.'
cd "$DOTFILES"

[ -f "./map.conf" ] || die "map.conf file not present in $DOTFILES"

nested_dir=""

link() {
  echo "$1 => $2"
}

# TODO: handle linking a specific thing, check if stuff exists, handle multiple nesting levels
while read -r map; do
  if [ ! -z "$map" ] && [[ ! "$map" == "#"* ]]; then
    mapping=($(echo "$map" | sed 's/^ *- /-/' | awk -F ': ' '{ print $1 " " $2 }'))

    # Top level items
    if [[ ! "${mapping[0]}" == "-"* ]]; then
      if [ -z "${mapping[1]}" ]; then
        nested_dir="${mapping[0]/:/}"
      else
        nested_dir=""
        link "${mapping[0]}" "${mapping[1]}"
      fi
    # Nested items
    else
      link "$nested_dir/${mapping[0]/-/}" "${mapping[1]}"
    fi
  fi
done < <(cat "./map.conf")



