#!/usr/bin/env bash
if ! command -v gpg &>/dev/null; then
  echo "gpg not installed." >&2
  exit 1
fi

if [ ! -z "$2" ]; then
  mkdir -p "$2"
  gpg --decrypt "$1" | tar xz -C "$2"
echo "Decrypted $1 into $2"
else
  gpg --decrypt "$1" | tar xz
echo "Decrypted $1 into ./"
fi
