#!/bin/sh
substring() {
  needle="$1"
  haystack="$2"
  [ "${haystack#*"$needle"}" != "$haystack" ]
}
current="$(xrandr | grep '^[^[:blank:]]')"
case "$(printf 'Single display\nMirror\nAuto' | dmenu -i -l 5 -p "Display config:")" in
  'Single display')
    cmd="xrandr --output eDP-1 --off"
    substring "HDMI-1 connected" "$current" && cmd="$cmd --output HDMI-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal"
    substring " DP-1 connected" "$current" && cmd="$cmd --output DP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal"
    substring " DP-2 connected" "$current" && cmd="$cmd --output DP-2 --off"
    $cmd
    ;;
  'Mirror')
    cmd="xrandr --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal"
    substring "HDMI-1 connected" "$current" && cmd="$cmd --output HDMI-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal"
    substring " DP-1 connected" "$current" && cmd="$cmd --output DP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal"
    substring " DP-2 connected" "$current" && cmd="$cmd --output DP-2 --off"
    $cmd
    ;;
  'Auto')
    xrandr --auto;;
  *);;
esac
