#!/bin/sh

case "$(printf 'Single display\nMirror\nAuto' | dmenu -i -l 5 -p "Display config:")" in
  'Single display')
    xrandr \
      --output eDP-1 --off \
      --output HDMI-1 --off \
      --output DP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
      --output DP-2 --off
    ;;
  'Mirror')
    xrandr \
      --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal \
      --output HDMI-1 --off \
      --output DP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
      --output DP-2 --off
    ;;
  'Auto')
    xrandr --auto;;
  *);;
esac
#

