#!/bin/sh
# This script uses `dragon` to provide drag-and-drop functionality.
# Provide one or more filenames, and you'll get a window from which you can
# drag.
command -v dragon-drag-and-drop || { printf "Install mwh/dragon\n" >&2 && exit 1; }
setsid -f dragon-drag-and-drop "$@"
