#!/bin/sh
# dwmblocks script for brightness information
case "$BUTTON" in
  1)
    pkill -RTMIN+3 dwmblocks;;
  3) brightnessctl set '100%';;
  4)
    brightnessctl set '10%-'
    pkill -RTMIN+3 dwmblocks
    ;;
  5)
    brightnessctl set '10%+'
    pkill -RTMIN+3 dwmblocks
    ;;
  6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

printf ' %s' "$(brightnessctl --machine-readable | cut -d, -f4)"
