#!/bin/sh
# dwmblocks script for bluetooth

# Interfaces:
# (list with `nmcli --get-values GENERAL.DEVICE,GENERAL.TYPE device show`)
wired=enp0s31f6
wireless=wlp0s20f3
# there's probably a way to change these but I'd have to know all files to update...

case "$BUTTON" in
  1)
    pgrep -f nmtui || "$TERMINAL" -e bluetoothctl
    pkill -RTMIN+8 dwmblocks
    ;;
  3)
    notify Bluetooth "Toggling bluetooth..."
    rfkill toggle bluetooth
    pkill -RTMIN+8 dwmblocks
    ;;
  6) "$TERMINAL" -e "$EDITOR" "$0"
    ;;
esac

bt="$(bluetoothctl show)"
if bluetoothctl devices | cut -f2 -d' ' | while read uuid; do bluetoothctl info $uuid; done | grep '^\s*Connected: yes' >/dev/null 2>&1; then
  printf ' 🔗'
elif [ "$bt" = "No default controller available" ]; then
  printf " 🛑"
elif printf '%s' "$bt" | grep '^\s*Powered: no' >/dev/null 2>&1; then
  printf ' ❌'
elif printf '%s' "$bt" | grep '^\s*Powered: yes' >/dev/null 2>&1; then
  printf ''
fi
