#!/bin/sh
case "$BUTTON" in
  1)
    pgrep -f backlight-brightness || setsid -f "$TERMINAL" -e backlight-brightness
    pkill -RTMIN+3 dwmblocks;;
  3) backlight-brightness -s 100 ;;
  4)
    backlight-brightness '-10'
    pkill -RTMIN+3 dwmblocks
    ;;
  5)
    backlight-brightness '+20'
    pkill -RTMIN+3 dwmblocks
    ;;
  6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

paste -d '/' /sys/class/backlight/*/actual_brightness /sys/class/backlight/*/max_brightness
