#!/bin/sh
# dwmblocks script for battery information
case "$BUTTON" in
  6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

status="$(battery | tac | tr -d '\n' | sed '
    s/Charging/⚡ /;
    /Discharging[01][0-9]$/s/Discharging/‼ /;
    s/Discharging/🔋 /;
    s/Not charging/⛔/;
    s/Full/✅/;
    s/Unknown/‽‽/' \
  | tac | tr -d '\n')"

if command -v upower >/dev/null 2>&1; then
  time_remaining=" ($(upower -i /org/freedesktop/UPower/devices/battery_BAT0 \
    | awk -F': ' '
        /^  *time to / {
          sub("^ *", "", $2);
          sub(" minutes", "min", $2);
          print $2
        }'))"
fi
case "$status" in
  ‼*) notify "Battery low" "$status%" battery critical;;
  ✅*) notify "Battery charged" "$status%" battery;;
esac
printf "%s%%%s\n" "$status" "${time_remaining:-}"
