#!/bin/sh
# dwmblocks script for battery information
case "$BUTTON" in
  6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

status="$(battery | tac | tr -d '\n' | sed '
    s/Charging/⚡ /;
    /Discharging[01][0-9]$/s/Discharging/‼ /;
    s/Discharging/🔋 /;
    s/Not charging/⛔/;
    s/Full/✅/;
    s/Unknown/‽‽/' \
  | tac | tr -d '\n')"

case "$status" in
  ‼*) notify "Battery low" "$status%" battery critical;;
  ✅*) notify "Battery charged" "$status%" battery;;
esac
printf "%s%%\n" "$status"
