#!/usr/bin/env bash
if ! command -v gpg &>/dev/null; then
  echo "gpg not installed." >&2
  exit 1
fi

export GPG_TTY=$(tty)

if [ -f "$1" ]; then
elif [ -d "$1" ]; then
else
  echo "File doesn't exist or not supported."
fi
if [ ! -z "$2" ]; then
  mkdir -p "$2"
  (cd "${1%/*}" && tar cz "${1##*/}") | gpg -c --cipher-algo aes256 -o "${2%/}"/"${1##*/}.tgz.gpg"
  echo "Encrypted $1 into $2"
else
  (cd "${1%/*}" && tar cz "${1##*/}")  | gpg -c --cipher-algo aes256 -o "${1##*/}.tgz.gpg"
  echo "Encrypted $1 into ."
fi
