#!/usr/bin/env bash
set -x
if ! command -v gsettings &>/dev/null; then
  echo "gsettings not installed." >&2
  exit 1
fi

theme=$(gsettings get org.gnome.Terminal.Legacy.Settings theme-variant | tr -d "'")
if [ "$theme" = "light" ]; then
  feh --bg-scale "/home/zeroalpha/Pictures/Backgrounds/light.jpg"
else
  feh --bg-fill "/home/zeroalpha/Pictures/Backgrounds/dark.jpg"
fi
