#!/usr/bin/env bash
[ -z "$WORKON_HOME" ] && { echo '$WORKON_HOME not set'; exit 1; }
if ! command -v lsvirtualenv &>/dev/null; then
  echo "virtualenvwrapper not installed." >&2
  exit 1
fi
if ! command -v gfind &>/dev/null; then
  echo "gfind not installed." >&2
  exit 1
fi

for i in $(lsvirtualenv -b); do
  gfind "$WORKON_HOME"/"$i" -type l -xtype l -delete;
  virtualenv "$WORKON_HOME"/"$i";
done