#!/usr/bin/env bash

[ -z "$WORKON_HOME" ] && { echo '$WORKON_HOME not set'; exit 1; }
if ! command -v gfind &>/dev/null; then
  echo "gfind not installed." >&2
  exit 1
fi

for i in $(find $WORKON_HOME -maxdepth 1 -type d -mindepth 1); do
  gfind "$i" -type l -xtype l -delete;
  virtualenv "$i";
done