#!/bin/sh
# Play the top pronunciation from forvo.com for a phrase & language
die() { printf '%s\n' "$1" >&2 && exit 1; }
checkdeps() {
  for com in "$@"; do
    command -v "$com" >/dev/null 2>&1 \
      || { printf '%s required but not found.\n' "$com" >&2 && exit 1; }
  done
}
checkdeps curl pup awk base64 mpv

[ $# -eq 2 ] || die "Usage: forvo PHRASE ISO_LANG_CODE"
phrase_encoded="$(printf '%s' "$1" | sed 's/ /%20/g')"
lang="$2"
search_url="https://forvo.com/search/$phrase_encoded/$lang"
search_result="$(curl -sL "$search_url")"
audio_path="$(printf '%s' "$search_result" \
  | pup '.results_match li div.play:first-of-type attr{onclick}' \
  | awk -F '&#39;' '{print $2 }' \
  | base64 -d)"
if [ -z "$audio_path" ]; then
  if [ "$(printf '%s' "$search_result" | pup '.results_match li span.lang_rec text{}')" = "Pending pronunciation" ]; then
    die "Not yet recorded."
  fi
  die "Not found."
fi
audio_url="https://audio.forvo.com/mp3/$audio_path"
mpv -loop "$audio_url"
