#!/bin/sh
# Fzf search engine, print search URL
elvi="$(surfraw -elvi | sed '1,/LOCAL/d' | fzf | cut -f1)"
[ -z "$elvi" ] && exit
query="$(fzf --print-query --prompt="$elvi >> Search: " --info=hidden --layout=reverse </dev/null)"
surfraw -p "$elvi" "$query"
