#!/usr/bin/env ruby
require 'faraday'
require 'json'

class Page
  def initialize name
    @url = "https://api.github.com/repos/thezeroalpha/#{name}/pages/builds"
    @name = name
  end

  def get_status
    if @etag
      response = Faraday.get("#{@url}/latest", nil, authorization: "token #{ENV['GITHUB_AUTH_TOKEN']}", if_none_match: @etag)
    else
      response = Faraday.get("#{@url}/latest", nil, authorization: "token #{ENV['GITHUB_AUTH_TOKEN']}")
    end

    if response.success?
      j = JSON.parse(response.body)
      @etag = response.headers['etag']
      @code = response.status
      @created_at = j['created_at']
      @updated_at = j['updated_at']
      @status = j['status']
      @error = j['error']['message']
    elsif response.status == 304
      @etag = response.headers['etag']
      @code = response.status
    else
      @code = response.status
    end
  end

  def build
    response = Faraday.post(@url, nil, authorization: "token #{ENV['GITHUB_AUTH_TOKEN']}")
    if response.success?
      j = JSON.parse(response.body)
      @code = response.status
      @etag = response.headers['etag']
      @status = j['status']
    else
      @code = response.status
    end
  end
  def to_str
    str = "#{@name}: #{@status}"
    str += ", #{@updated_at}" unless @updated_at.nil?
    str += ", #{@error}" unless @error.nil?
    str += "not found" if @code == 404
    str += "."
  end
end

subcmd = ARGV.shift

if ["build", "b"].include? subcmd
  if ARGV.size > 0
    values = ARGV.map do |page|
      Thread.new do
        p = Page.new page
        p.build
        p.to_str
      end
    end.map(&:value)

    puts "Builds:"
    values.each { |v| puts v }
  else
    puts "Provide the name of one or more repositories."
  end
elsif ["watch", "w", "status", "s"].include? subcmd
  if ARGV.size > 0
    pages = ARGV.map { |p| Page.new p }
    while true
      values = pages.map do |page|
        Thread.new { page.get_status; page.to_str }
      end.map(&:value)

      system "clear"
      puts "Status:"
      values.each { |v| puts v }
    end
  else
    puts "Provide the name of one or more repositories."
  end
elsif ["rate", "remaining", "r"].include? subcmd
  response = Faraday.get("https://api.github.com/rate_limit", nil, authorization: "token #{ENV['GITHUB_AUTH_TOKEN']}")
  j = JSON.parse(response.body)
  core = j['resources']['core']
  puts "Requests remaining: #{core['remaining']}/#{core['limit']}"
else
  puts <<-YEET
  Available commands:

  watch, w, status, s       print out the status of pages
  build, b                  trigger a build of a page
  rate, remaining, r        print out the number of remaining API requests
  YEET

end
