#!/bin/sh
HEIGHT="$2"
[ -z "$2" ] && HEIGHT="$(tput lines)"
os=$(uname -s | tr '[:upper:]' '[:lower:]')
case "$os" in
  linux*)
    command -v chafa 1>/dev/null 2>&1 || { printf "Please install chafa\n" && exit 1; }
    chafa --fill=block --symbols=block -c 256 -s 80x"$HEIGHT" "$1"
    ;;
  darwin*)
    command -v chafa 1>/dev/null 2>&1 || { printf "Please install chafa\n" && exit 1; }
    chafa -c 256 -s 80x"$HEIGHT" "$1"
    ;;
  msys*|cygwin*|mingw*|nt|win*)
    printf "Windows not supported.\n"
    ;;
  *)
    printf "Operating system %s is unknown.\n" "$os"
    ;;
esac
