#!/bin/sh
# Cross-platform terminal image preview script.
HEIGHT="$2"
[ -z "$2" ] && HEIGHT="$(tput lines)"
os=$(uname -s | tr '[:upper:]' '[:lower:]')
case "$os" in
  linux*)
    if command -v catimg 1>/dev/null 2>&1; then
      catimg -H "$HEIGHT" "$1"
    elif command -v chafa 1>/dev/null 2>&1; then
      chafa --fill=block --symbols=block -c 256 -s 80x"$HEIGHT" "$1"
    else
      printf "Please install catimg or chafa\n" >&2 && exit 1
    fi
    ;;
  darwin*)
    catimg -H "$HEIGHT" "$1"
    ;;
  msys*|cygwin*|mingw*|nt|win*)
    printf "Windows not supported.\n"
    ;;
  *)
    printf "Operating system %s is unknown.\n" "$os"
    ;;
esac
