#!/usr/bin/env bash
read -rp "Execute cleanup in $(pwd)?" -n 1 -s conf
case "$conf" in
  Y|y)
    ;;
  *)
    echo "OK nothing happens"
    exit 1
    ;;
esac

set -x
sed -i  's:\.\./_resources:\./_resources:g' *.html
mv * ../
cd ..
find . -type d -empty -depth -delete

