#!/bin/sh
[ -z "$1" ] && { "$BROWSER"; exit; }

case "$1" in
  *mkv|*webm|*mp4|*youtube.com/watch*|*youtube.com/playlist*|*youtu.be*|*hooktube.com*|*bitchute.com*|*videos.lukesmith.xyz*)
    notify 'Starting mpv' "Opening $1..." 'linkhandler'
    setsid -f mpvq "$1" 1>/dev/null 2>&1
    ;;
  *png|*jpg|*jpe|*jpeg|*gif)
    notify 'Starting sxiv' "Opening $1..." 'linkhandler'
    curl -sL "$1" > "/tmp/$(printf "%s" "$1" | sed "s/.*\///")" \
      && sxiv -a "/tmp/$(printf "%s" "$1" | sed "s/.*\///")"  1>/dev/null 2>&1 &
    ;;
  *gifv)
    setsid -f mpv -loop "$1" 1>/dev/null 2>&1
    ;;
  *mp3|*flac|*opus|*mp3?source*)
    setsid -f mpv --volume=50 "$1" 1>/dev/null 2>&1
    ;;
  *reddit.com*)
    tuir "$1"
    ;;
  *news.ycombinator.com*|*lean-forward.github.io*) # readability whitelist
    w3m -config ~/.config/w3m/config "$1"
    ;;
  http://*|https://*)   # everything else gets filtered through readability
    go-readability "$1" | w3m -config ~/.config/w3m/config -T text/html
    ;;
  '!http'*)
    os=$(uname -s | tr '[:upper:]' '[:lower:]')
    case "$os" in
      linux*)
        setsid -f brave "${1##!}"
        ;;
      darwin*)
        open -a 'Brave Browser' "${1##!}"
        ;;
      msys*|cygwin*|mingw*|nt|win*)
        printf "Windows not supported.\n" >&2
        ;;
      *)
        printf "Operating system %s is unknown.\n" "$os"
        ;;
    esac
    ;;
  *)
    if [ -f "$1" ]; then "$EDITOR" "$1"
    else open "$1" >/dev/null 2>&1
    fi
    ;;
esac

