#!/bin/sh
if [ -z "$BW_SESSION" ]; then
  if [ -n "$BW_SESHFILE" ] && [ -f "$BW_SESHFILE" ]; then
    BW_SESSION="$(cat "$BW_SESHFILE")"
  else
    BW_SESSION="$(bw unlock --raw)"
    [ $? -eq 0 ] || { printf "Could not unlock vault.\n" && exit 1; }
  fi
  export BW_SESSION
fi
mbsync -c /Users/alex/.config/mbsync/mbsyncrc -Va
notmuch new
notification_str=""
for i in ~/.local/share/mail/*/[Ii][Nn][Bb][Oo][Xx]/new; do
  mailbox_name="$(printf "%s" "$i" | sed 's:^.*mail/::; s:/[Ii][Nn][Bb][Oo][Xx]/new.*$::')"
  num_new_messages="$(find "$i"/* -type f 2>/dev/null | wc -l)"
  [ "$num_new_messages" -gt 0 ] \
    && notification_str="${notification_str}
$(printf "%s: %d" "$mailbox_name" "$num_new_messages")"

done

{ [ -n "$notification_str" ] && notify "Mail synced" "$notification_str" mail; } \
  || notify "Mail synced" "No new messages" mail
