#!/usr/bin/env bash
# set -x
if ! command -v simple-mtpfs &>/dev/null; then
  echo "simple-mtpfs not installed." >&2
  exit 1
fi

mountdir="/Users/alex/phone"
clean_up() {
  echo "Exiting..."
  if kill -0 "$mtpfs_pid" &> /dev/null; then
    kill "$mtpfs_pid"
    wait "$mtpfs_pid"
  fi
  [ ! -d "$mountpoint" ] || rmdir "$mountpoint";
  [ ! -L "$mountdir" ] || unlink "$mountdir";
}
trap clean_up INT TERM EXIT

try_to_mount() {
  echo "Mounting phone..."
  simple-mtpfs -f "$mountpoint" &
  mtpfs_pid=$!
}

mountpoint=$(mktemp -d)
try_to_mount
ln -s "$mountpoint" "$mountdir"
echo "Mounted at $mountdir (=> $mountpoint)."
echo "Send interrupt to unmount."
wait
