#!/usr/bin/env bash
[ $# -eq 2 ] || { terminal-notifier -title "Not enough arguments" -message "Need exactly 2 arguments." && exit 1; }
what="$1"
where="$2"
downloads="$HOME/Downloads/"
audiodir="$downloads/newsboat/audio"
videodir="$downloads/newsboat/video"
logfile="$HOME/.cache/newsboat-download.log"
title=$(youtube-dl --ignore-config --get-title --get-duration --get-description "$where" 2>/dev/null)

terminal-notifier -title "Started $what download" -message "Downloading \"$title\"" -group "$where"
case "$what" in
  "aonly")
    mkdir -p "$audiodir"
    youtube-dl --add-metadata -xic -f bestaudio/best -o "$audiodir/%(title)s-%(creator)s.%(ext)s" "$where" 2>&1 >> "$logfile"
    ;;
  "av")
    youtube-dl --add-metadata -ic --write-sub --embed-subs -o "$videodir/%(title)s-%(creator)s.%(ext)s" "$where" 2>&1 >> "$logfile"
    ;;
  *)
    terminal-notifier -title "Error" -message "Download option not valid" -group "$where"
    exit 1
    ;;
esac
terminal-notifier -title "Download complete" -message "Downloaded \"$title\"" -group "$where"
