#!/bin/sh
set -e

notidie() {
  notify "$1" "$2" news
  exit 1
}

os=$(uname -s | tr '[:upper:]' '[:lower:]')
case "$os" in
  darwin*)
    while pgrep RotMG; do sleep 60; done
    /usr/local/bin/alacritty -e /Users/alex/.local/share/cargo/bin/rbw unlock
    /Users/alex/.local/share/cargo/bin/rbw unlocked || notidie "Newsboat: error reloading" "Vault is locked"
    ;;
esac

newsboat -x reload 2>&1 || notidie "Newsboat: error reloading" "Unable to reload"
newsboat -x print-unread | xargs -I{} notify 'Newsboat reloaded' "{}" news
