#!/bin/sh
set -e

notidie() {
  terminal-notifier -group news -sender news -title "$1" -message "$2"
  exit 1
}

newsboat -x reload 2>&1 || notidie "Newsboat: error reloading" "Unable to reload"
newsboat -x print-unread | xargs -I{} terminal-notifier -group news -sender news -title 'Newsboat reloaded' -message "{}"
