#!/bin/sh
[ $# -gt 0 ] || { printf "File required in argument.\n" && exit 1; }
case "$1" in
  http*) linkhandler "$@";;
  *)
    case $(file --mime-type "$1" -bL) in
      text/*|application/json|inode/x-empty) { [ -n "$VIM_TERMINAL" ] && vimsend "$1"; } || ${EDITOR:-vim} "$1";;
      image/*) setsid -f sxiv "$@" 2>&1;;
      application/epub*) setsid -f ebook-viewer "$1" >/dev/null 2>&1;;
      application/pdf*) setsid -f zathura "$1" >/dev/null 2>&1;;
      application/x-sc|application/vnd.openxmlformats-officedocument.spreadsheetml.sheet) sc-im "$1";;
      video/*) mpvq "$@";;
      audio/*) mpv --no-audio-display --no-video --volume=50 "$1";;
      application/x-mach-binary) ;;
      application/octet-stream)
        case "$1" in
          *.mp3) mpv --no-audio-display --no-video --volume=50 "$1";;
          *.dmg) setsid -f open "$@" > /dev/null 2>&1;;
        esac
        ;;
      *) setsid -f open "$@" > /dev/null 2>&1;;
    esac;;
esac
