#!/bin/sh
#/usr/bin/pactl set-sink-volume 0 +5%
SINK=$( pactl list short sinks | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' | head -n 1 )
NOW=$( pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )
if [ "$1" = "up" ]; then
  /usr/bin/pactl set-sink-mute "$SINK" 0
  if [ $((NOW+5)) -le 100 ]; then
    /usr/bin/pactl set-sink-volume "$SINK" "+5%"
  else
    /usr/bin/pactl set-sink-volume "$SINK" "100%"
  fi
elif [ "$1" = "down" ]; then
  if [ $((NOW-5)) -gt 0 ]; then
    /usr/bin/pactl set-sink-volume "$SINK" "-5%"
  else
    /usr/bin/pactl set-sink-volume "$SINK" "0%"
    /usr/bin/pactl set-sink-mute "$SINK" 1
  fi
fi
