#!/usr/bin/env bash
if [ $# -ne 2 ]; then
  echo 'Usage: pass-import-txt [file] [path]'
  exit 1
fi

dest="${2%/}"
echo "$(tput setaf 6)This is what's gonna happen:"
while read -r line; do 
  arr=(${line//:/ }); 
  echo "echo ${arr[1]} | pass insert --multiline $dest/${arr[0]}"; 
done < "$1"

echo -ne "\n$(tput setaf 3)Is this OK? [Y/n]"
read -rn 1 -s CONF
case $CONF in
  Y|y)
    echo -e "\n$(tput setaf 6)OK, importing...$(tput sgr0)"
    ;;
  *) exit 1;;
esac
while read -r line; do 
  arr=(${line//:/ }); 
  echo "${arr[1]}" | pass insert --multiline "$dest"/"${arr[0]}"; 
done < "$1"
echo "$(tput setaf 2)Done."
