#!/usr/bin/env bash

rootdir="$MUSIC_DIR"
mpv_options="--no-video --really-quiet --volume=50"
mpv_options_vis="--no-video --really-quiet --volume=50 --script=$HOME/.config/mpv/visualizer.lua -vo caca"
mpv_options_noart="--no-video --volume=50"

play_track() {
   trap '' INT
   vis=0
   if [ -z "$2" ]; then
      vis=1
   fi
   if [[ "$1" == "all" ]]; then
      track=$(ls|sort -n|head -1)
      ffmpeg -i "$track" art.jpg &>/dev/null

      if [ -e "art.jpg" ] && [ $vis -eq 1 ]; then
         im2a art.jpg -T
         mpv "$(pwd)" $mpv_options
         rm art.jpg
      elif [ $vis -eq 1 ]; then
         mpv "$(pwd)" $mpv_options_vis
      else
         clear
         mpv "$(pwd)" $mpv_options_noart
      fi
   else
      if [ ! -e "$1" ]; then
         echo "File does not exist: $1"
      else
         ffmpeg -i "$1" art.jpg &>/dev/null 
         if [ -e "art.jpg" ] && [ $vis -eq 1 ] ; then
            im2a art.jpg -T
            mpv "$(pwd)/$1" $mpv_options
            rm art.jpg
         elif [ $vis -eq 1 ]; then
            mpv "$(pwd)/$1" $mpv_options_vis
         else
            clear
            mpv "$(pwd)/$1" $mpv_options_noart
         fi
      fi
   fi
   trap clean_up INT
   clear
}
read_letter() {
   read -sn 1 -p "Continue? [Y/n]" CONF
}
clean_up() {
   trap - INT
   clear
   exit 0
}

init_check() {
   deps=(ffmpeg mpv im2a)
   for dep in ${deps[@]}; do
      if ! command -v $dep &>/dev/null; then
         echo "Please install $dep."
         exit 1
      fi
   done
}

init_check
cd "$rootdir"
trap clean_up INT
clear
echo "Music Player v1"
while :; do
   read -e -p "> " -a INPUT
   CMD=${INPUT[0]}
   ARGS=("${INPUT[@]:1}")
   case $CMD in
      "cd")
         if [ -z "$ARGS" ]; then
            echo "No directory provided."
         elif [[ "$ARGS" == "/" ]]; then
            cd "$rootdir"
         elif [ ! -d "$ARGS" ]; then
            echo "Directory does not exist."
         else
            pushd "$ARGS" &>/dev/null
            if [[ $(pwd) == $rootdir* ]]; then
               popd &>/dev/null
               cd "$ARGS"
            else
               echo "Cannot enter this directory."
               popd&>/dev/null
            fi
         fi
         ;;
      "play")
         if [ -z "$ARGS" ]; then
            echo "No file provided."
         else
            play_track "${ARGS[@]}"
         fi
         ;;
      "ls")
         if command -v less &> /dev/null; then
            ls -C | less
         elif command -v more &> /dev/null; then
            ls -C | more
         else
            ls -C
         fi
         ;;
      "pwd")
         dir=$(pwd)
         if [[ $dir == $rootdir ]]; then
            echo "/"
         else
            echo ${dir##$rootdir}
         fi
         ;;
      "q"|"quit")
         clean_up;;
      "help"|"h"|"?")
         echo "Commands:"
         echo "cd                                change to artist/album directory"
         echo "pwd                               print current directory"
         echo "ls                                list contents of current directory"
         echo "play all                          play everything in current directory"
         echo "play [file]                       play specific track"
         echo "play [all|file] [something]       disable visualiser/art"
         ;;
      *)
         echo "Command does not exist."
         echo "Type 'help' to show commands."
         ;;
   esac
done
