#!/bin/sh
die() { printf '%s\n' "$1" >&2 && exit 1; }

command -v tput > /dev/null 2>&1 || die "tput not installed."

[ -z "$(printf '%s' "$1" | tr -d '0-9')" ] || die 'Usage: tput-colors [number]'
# Print out 16 colors by default
[ "$#" -eq 0 ] && set -- 16

tput init >/dev/null 2>&1

: $((i=0))
while [ $((i < $1)) -ne 0 ]; do
  case $i in 0) pref="(black)";; 1) pref="(red)";; 2) pref="(green)";; 3) pref="(yellow)";; 4) pref="(blue)";; 5) pref="(magenta)";; 6) pref="(cyan)";; 7) pref="(white)";; *) pref="";; esac
  echo "$(tput sgr0)$i$pref $(tput setaf "$i")sample text"
  i=$((i+1))
done

