#!/bin/sh
[ -d ./public ] || { printf "No public/ folder present in current directory\n" && exit 1; }
destdir=/var/www/"$(basename "$(pwd)")"

ping -c 1 vps >/dev/null 2>&1 || { printf "Host 'vps' not reachable.\n" && exit 1; }
printf "Upload public/ to vps:%s? [Y/n] " "$destdir"
read -r conf
case "$conf" in
  Y|y|Yes|yes)
    ;;
  *)
    echo "User cancelled."
    exit 0
    ;;
esac

# Use long names for clarity
rsync \
  --partial \
  --update \
  --recursive \
  --copy-links \
  --compress \
  --prune-empty-dirs \
  --delete-after \
  --verbose \
  --human-readable \
  --progress \
  public/ vps:"$destdir"
