#!/usr/bin/env bash
# this should have low priority
renice 20 $$
while :; do
  clear;
  for ((;;)); do
    for i in {1..360}; do
      tput cup 0 0;
      ruby qlobe_quine.rb $i;
    done;
  done;
done 2>/dev/null
