#!/bin/sh
# vim: foldmethod=syntax foldlevel=1
set_macos() {
  case "$1" in
    dark) dark="true";;
    light) dark="false";;
  esac
  osascript - <<EOF
on run
  tell application "System Events"
    tell appearance preferences
      set dark mode to $dark
    end tell
  end tell
end run
EOF
}

set_iterm2() {
  ITERM2_COOKIE=$(osascript -e 'tell application "iTerm2" to request cookie') ~/Library/ApplicationSupport/iTerm2/iterm2env/versions/3.7.5/bin/python3 \
    - "$1" <<EOF
#!/usr/bin/env python3
import iterm2
from sys import argv
async def main(connection):
    profiles = [p for p in await iterm2.PartialProfile.async_query(connection) if p.name.startswith("Default ")]
    if len(argv) > 1:
        theme = str(argv[1])
    else:
        import subprocess
        result = subprocess.run(['osascript', '-e', 'tell application "System Events" to tell appearance preferences to return (get dark mode as text)'], stdout=subprocess.PIPE)
        theme = str(result.stdout.rstrip().decode("utf-8"))
    for p in profiles:
        if "Light" in p.name and theme == "light":
            await p.async_make_default()
            return
        elif "Dark" in p.name and theme == "dark":
            await p.async_make_default()
            return
try:
    iterm2.run_until_complete(main)
except Exception as exception:
    print("Error: ", exception)
EOF
}

set_terminal_and_wallpaper() {
  if [ "$1" = "light" ]; then
    /usr/local/bin/wal --saturate 0.8 -i ~/Pictures/Backgrounds/light.jpg -l;
  else
    /usr/local/bin/wal -i ~/Pictures/Backgrounds/dark.jpg;
  fi
}

set_p10k() {
  [ -f ~/.dotfiles/shell/p10k-"$1".zsh ] && ln -sf ~/.dotfiles/shell/p10k-"$1".zsh ~/.p10k.zsh
}

set_tmux() {
  [ -f ~/.dotfiles/tmux/tmux-"$1".conf ] && ln -sf ~/.dotfiles/tmux/tmux-"$1".conf ~/.config/tmux/tmux.conf
}

[ $# -eq 1 ] || { printf "Arguments: dark, light\n" && exit 1; }
case "$1" in
  dark) THEME="dark";;
  light) THEME="light";;
  *) printf "Arguments: dark, light\n" && exit 1;;
esac

os=$(uname -s | tr '[:upper:]' '[:lower:]')
case "$os" in
  darwin*)
    set_macos "$THEME"
    set_iterm2 "$THEME"
    ;;
esac

set_terminal_and_wallpaper "$THEME"
set_p10k "$THEME"
set_tmux "$THEME"
