#!/usr/bin/env bash

# Preliminary tests
if [[ $(uname -s) == "Darwin" ]]; then
  ss_dir_orig="$(defaults read com.apple.screencapture location)"
elif [[ $(uname -s) == "Linux" ]] && command -v gsettings &> /dev/null; then
  ss_dir_orig="$(gsettings get org.gnome.gnome-screenshot auto-save-directory)"  
else
  echo "Not supported on this system."
  exit 1
fi

if [ $# -eq 0 ]; then
  echo "Need a new directory!"
  echo "Usage:"
  echo "ss-interceptor [NEW_LOCATION]"
  exit 1
fi

cleanup() {
  echo "..."
  echo "Done. Screenshots saved to $new_ss_dir."
  if [[ $(uname -s) == "Darwin" ]]; then
    defaults write com.apple.screencapture location "$ss_dir_orig"
  elif [[ $(uname -s) == "Linux" ]]; then
    gsettings set org.gnome.gnome-screenshot auto-save-directory "$ss_dir_orig"
  fi
  exit 0
}

trap cleanup exit

echo "= Screenshot Interceptor ="

if [ "${1:0:1}" = "." ]; then
  new_ss_dir="$(pwd)/${1#*/}"
elif [ "${1:0:1}" != "/" ]; then
  new_ss_dir="$(pwd)/$1"
else
  new_ss_dir="$1"
fi


if ! [ -d "$new_ss_dir" ]; then
  echo "Creating $new_ss_dir..."
  mkdir -p "$new_ss_dir"
fi

if [[ $(uname -s) == "Darwin" ]]; then
  defaults write com.apple.screencapture location "$new_ss_dir"
elif [[ $(uname -s) == "Linux" ]]; then
  gsettings set org.gnome.gnome-screenshot auto-save-directory "$new_ss_dir"
else
  echo "Error"
fi

echo "Saving screenshots to:"
echo "$new_ss_dir"
echo -e "\nPress Ctrl-C to stop..."

while :; do sleep 1; done
