#!/usr/bin/env bash
if ! command -v rsync &>/dev/null; then
  echo "rsync not installed." >&2
  exit 1
fi

do_rsync() {
  rsync -uhamP --delete --stats  "$@"
}
die() {
  echo "$1" >&2
  exit 1
}
PHONE_DIR="$HOME/phone/Card/Music"
MUSIC_DIR="${MUSIC_DIR:-$HOME/Music}"

[ -d "$PHONE_DIR" ] || die "Phone not present, expected at $PHONE_DIR"
[ -d "$MUSIC_DIR" ] || die "Music dir not present, expected at $MUSIC_DIR"

less -fR <(do_rsync "$MUSIC_DIR"/ "$PHONE_DIR" -n)

read -rp "Execute? [Y/n]" -n 1 -s conf
echo

case "$conf" in
  Y|y) do_rsync "$MUSIC_DIR"/ "$PHONE_DIR";;
  *) die "User cancelled.";;
esac

