#!/usr/bin/env bash
die() {
  echo "$1" >&2
  exit 1
}

process_file() {
  echo "Processing $1"
  tr '\r' '\n' < "$1" | sed 's:^/Volumes.*Music/:../Music/:' > "$PHONE_DIR"/"${1##*/}"
}

PHONE_DIR="$HOME/phone/Card/Playlists"

[ -d "$PHONE_DIR" ] || die "Phone not present, expected at $PHONE_DIR"
[ $# -ge 1 ] || die "Need something to act on."

for i in "$@"; do
  if [ -d "$i" ]; then
    while read -r f; do
      process_file "$f"
    done < <(find "$i" -name "*.m3u" -type f -maxdepth 1)
  elif [ -f "$i" ]; then
    if [[ "$i" == *.m3u ]]; then
      process_file "$i"
    else
      echo "Could not process $i"
    fi
  fi
done
