#!/usr/bin/env bash
if ! command -v tput &> /dev/null; then
  echo "tput not installed."
  exit 1
fi

if ! [[ "$1" =~ ^[0-9]+$ ]]; then
  echo "Usage: tput-colors [number]"
  exit 1
fi
tput init &> /dev/null
hr() { tput sgr0; for ((i=0; i<$(tput cols); i++)); do echo -n "#"; done; echo; }
hr
echo "Colors for tput:"
hr
if [ $# -eq 0 ]; then
  for ((i=1; i<=$(tput colors); i++)); do
    echo "$(tput sgr0)$i $(tput setaf $i)sample text"
  done
else
  for ((i=1; i<=$1; i++)); do
    echo "$(tput sgr0)$i $(tput setaf $i)sample text"
  done
fi
hr
