#!/usr/bin/env bash
# vim: foldmethod=marker foldlevel=0:

# Function/variable definitions {{{
OPTIND=1
all_casks=0
no_casks=0
all_formulas=0
no_formulas=0
all=0
none=0
select_casks=0
sudo_auth=0
greedy=1

TICK="\e[1;32m\u2714\e[0m"
CROSS="\e[1;31m\u2718\e[0m"

echo_succ() {
   echo -e "[ $TICK ] \e[1;32m$1\e[0m"
}
echo_err() {
   echo -e "[ $CROSS ] \e[1;31m$1\e[0m"
}
echo_warn() {
   echo -e "[\e[1;34m!!!\e[0m] \e[1;34m$1\e[0m"
}
echo_progress() {
   echo -e "[\e[1;36m...\e[0m] \e[1;36m$1\e[0m"
}
hr() {
   cols=$(tput cols)
   printf '#%.0s' $(seq 1 $cols)
}
# }}}

echo_progress "### STARTING UPDATE SCRIPT ###\n"

# Parse options/arguments {{{
while getopts "fcashFACn" opt; do
   case "$opt" in
      c)
         all_casks=1
         ;;
      f)
         all_formulas=1
         ;;
      a)
         all=1
         ;;
      s)
         select_casks=1
         ;;
      F)
         no_formulas=1
         ;;
      C)
         no_casks=1
         ;;
      A)
         none=1
         ;;
      n) 
         greedy=0;;
      h|*)
         echo "Update your Homebrew, Mac App Store, NPM, and PIP packages in one place."
         echo "Usage: updatemaster [-aAcCfFsh]"
         echo "Options:"
         echo "-c:		Upgrade all casks, without prompting."
         echo "-C:		Don't update any casks."
         echo "-f:		Upgrade all formulas, without prompting."
         echo "-F:		Don't upgrade any formulas."
         echo "-a:		Upgrade all casks and formulas."
         echo "-A:		Don't upgrade any Brew programs (maintenance only)."
         echo "-s:		Select which casks to upgrade."
         echo "-n:              Non-greedy"
         echo "-h:		Show this help text."
         echo
         echo "Options can be combined. For example:"
         echo "  updatemaster -fs"
         echo "Would update all formulas, and ask you to select which casks to upgrade."
         exit 0 
         ;;
   esac
done
# }}}

# Set up notification method {{{
if ! command -v notify &> /dev/null; then
   if command -v terminal-notifier &> /dev/null; then
      notify() { terminal-notifier -title "$1" -message "$2" -activate com.googlecode.iterm2; }
   else
      echo_warn "terminal-notifier not found, defaulting to bell. Install terminal-notifier to get the most out of this script."
      notify() { echo -e '\a'; }
   fi
fi
# }}}

# Pre-authorize sudo {{{
trap exit INT
echo -e "Root permissions will be needed for global pip update.\n"
if sudo -v; then
   sudo_auth=1
else
   sudo_auth=0
fi
trap - INT
echo
# }}}

# Homebrew {{{
echo_progress "Homebrew update/upgrade."
if command -v brew &> /dev/null; then
   brew update;
   brew update > /dev/null;
   outdated="$(brew outdated)"
   if [ $greedy = 1 ]; then
      outdated_c="$(brew cask outdated --greedy)"
   else
      outdated_c="$(brew cask outdated)"
   fi
   echo

   # Programs {{{
   if [ $no_formulas = 1 ] || [ $none = 1 ]; then
      echo_succ  "No programs will be updated." 
   elif [ ${#outdated} = 0 ]; then
      echo -e "No programs to update." 
   else
      echo -e "To update:\n"
      brew outdated;
      notify "Brew: Finished reading updates" "Click to view outdated packages."
      if [ $all_formulas = 1 ] || [ $all = 1 ]; then
         brew upgrade
      else
         echo; read -sn 1 -p "Continue? [Y/n]" CONF

         case $CONF in
            [yY] )
               echo -e "\nContinuing with brew upgrade."
               brew upgrade;
               ;;
            * )
               echo -e "\nCancelled brew upgrade."
               ;;
         esac
      fi
   fi
   # }}}

   # Casks {{{
   if [ ${#outdated_c} = 0 ]; then
      echo_succ "No casks to update." 
   elif [ $no_casks = 1 ] || [ $none = 1 ]; then
      echo_succ "No casks will be updated."
   else
      echo -e "Casks to update:"
      if [ $greedy = 1 ]; then
         brew cask outdated --greedy;
      else
         brew cask outdated
      fi
      notify "Cask: Finished reading updates" "Click to view outdated casks."
      if [ $all_casks = 1 ] || [ $all = 1 ]; then
         if [ $greedy = 1 ]; then
            brew cask upgrade --greedy
         else
            brew cask upgrade
         fi
      elif [ $select_casks = 1 ]; then
         read -p "Casks to upgrade (empty string cancels upgrade): " -a CASKS;
         for i in ${CASKS[@]}; do
            if ! brew cask upgrade $i; then echo -e "Could not upgrade cask $i."; fi
         done 
      else
         read -sn 1 -p "Upgrade all? [Y(es)/n(o)/s(elect)] " CONF

         case $CONF in
            [Ss] | [Ss]elect )
               echo
               read -p "Which casks would you like to upgrade? " -a CASKS;
               for i in ${CASKS[@]}; do
                  if ! brew cask upgrade $i; then echo -e "Could not upgrade cask $i."; fi
               done 
               ;;
            [Yy] | [Yy]es )
               echo -e "\nContinuing with cask upgrade."
               brew cask upgrade --greedy;
               ;; 
            * )
               echo -e "\nCancelled cask upgrade."
               ;;
         esac
      fi
   fi
   # }}}

   # Final steps & cleanup {{{
   brew cleanup -s;
   brew cleanup --prune-prefix;
   brew doctor;
   brew missing;

   echo "Homebrew cache disk usage:"
   du -h "$(brew --cache)"
   echo "Remove with:"
   echo " rm -rf $(brew --cache)"

   echo "Backing up Brew installation..."
   brew bundle dump --force --file=~/.dotfiles/Brewfile;

   echo_succ "Backup complete."
   notify "Brewed." "All packages have been upgraded.";
   # }}}
else
   echo_err "brew not found."
   echo_err "Cannot upgrade Homebrew packages. Please do so manually."
fi
# }}}

hr

# Mac App Store (MAS) {{{
echo_progress "MAS update/upgrade."
if command -v mas &> /dev/null; then
   echo -e "MAS outdated:"
   outdated=$(mas outdated)

   if [ ${#outdated} = 0 ]; then
      echo_succ "Everything is up to date."
   else
      mas outdated
      read -sn 1 -p "Continue? [Y/n]" CONF

      case $CONF in
         [Yy] )
            echo_succ -e "Continuing with mas upgrade."
            mas upgrade;
            ;;

         * )
            echo -e "Cancelled mas upgrade."
            ;;
      esac
      notify "MAS Updated." "All apps at newest version."
   fi
else
   echo_err -e "mas not found. Install mas to update App Store apps on the command line."
   echo_err -e "Cannot update Mac App Store apps. Please do so manually."
fi
# }}}

hr

# Global NPM packages {{{
echo_progress "NPM global update/upgrade."
if command -v npm &> /dev/null; then
   outdated=$(npm outdated)
   if [ ${#outdated} = 0 ]; then
      echo_succ "Everything is up to date."
   else
      npm update -g
      npm install -g npm
      notify "NPM Update Finished" "See Terminal for info."
   fi
   npm cache verify
   echo_succ "NPM update complete."
else
   echo_err "npm not found."
   echo_err "Cannot update NPM packages. Please do so manually."
fi
# }}}

hr

# Global (sudo) pip {{{
echo_progress "Global pip."
if [ $sudo_auth -eq 1 ]; then
   if command -v sudo -H pip list &> /dev/null; then
      sudo -H pip freeze | grep -v '^\-e' | cut -d = -f 1 | xargs sudo -H pip install -U
      echo_succ "Global pip upgrade complete."
   else
      echo -e "Cannot upgrade global pip packages. Please do so manually."
   fi
else
   echo -e "Sudo not authorised."
fi
# }}}

hr

# Atom editor packages {{{
if command -v apm &> /dev/null; then
   echo_progress "Atom package upgrades"
   if apm outdated &> /dev/null; then
      apm upgrade --no-confirm;
      echo_succ "All packages upgraded."
   else
      echo_err "Cannot upgrade Atom packages. Please do so manually."
   fi
   notify "APM Upgrade Complete" "See Terminal for info."
else
   echo_err "Atom not installed (or APM not functioning properly)."
fi
# }}}

hr

# Ruby gems {{{
if command -v gem &> /dev/null; then
   gem cleanup
fi
# }}}
#
hr

echo_succ "All systems checked."
notify "All systems checked." "Everything you indicated should be upgraded."
