#!/bin/sh
set -e

notidie() {
  notify "$1" "$2" vdirsyncd
  exit 1
}

os=$(uname -s | tr '[:upper:]' '[:lower:]')
case "$os" in
  darwin*)
    while pgrep RotMG; do sleep 60; done
    while pgrep pinentry; do sleep 60; done
    ;;
esac

vdirsyncer sync || notify 'Error in vdirsyncer' 'Did not sync properly, check /tmp/vdirsyncd.std{out,err}' vdirsyncd
vdirsyncer metasync || notify 'Error in vdirsyncer' 'Did not sync properly, check /tmp/vdirsyncd.std{out,err}' vdirsyncd
