#!/usr/bin/env bash
if [ "$1" = "up" ]; then
  brightness="$(xrandr --verbose |grep Brightness |grep -o '[0-9].*')"
  gamma="$(xrandr --verbose | grep Gamma | tr -d ' \t\n' |  awk -F: '{ printf "%f:%f:%f", 1/$2, 1/$3, 1/$4 }')"
  if  ! [ "$brightness" = "1.0" ]; then
    step=${2:-"0.05"}
    result=$(echo "$brightness $step" | awk '{ if ($1+$2 > 1) printf "1.0"; else printf "%f", $1+$2 }')
    xrandr --output LVDS-0 --gamma "$gamma" --brightness "$result"
  fi
elif [ "$1" = "down" ]; then
  brightness="$(xrandr --verbose |grep Brightness |grep -o '[0-9].*')"
  gamma="$(xrandr --verbose | grep Gamma | tr -d ' \t\n' |  awk -F: '{ printf "%f:%f:%f", 1/$2, 1/$3, 1/$4 }')"
  if  ! [ "$brightness" = "0.0" ]; then
    step=${2:-0.05}
    result=$(echo "$brightness $step" | awk '{ if ($1-$2 < 0) printf "0.0"; else printf "%f", $1-$2 }')
    xrandr --output LVDS-0 --gamma "$gamma" --brightness "$result"
  fi
elif [ "$1" = "gamma" ]; then
  brightness="$(xrandr --verbose |grep Brightness |grep -o '[0-9].*')"
  if [ "$2" = "night" ]; then
    xrandr --output LVDS-0 --gamma "1.1:0.7:0.6" --brightness "$brightness"
  else
    xrandr --output LVDS-0 --gamma "$2" --brightness "$brightness"
  fi
elif [ "$1" = "get" ]; then
  if [ "$2" = "brightness" ]; then
     result=$(xrandr --verbose |grep Brightness | grep -o '[0-9\.]*')
     echo "$result" | awk '{ printf "%d%%", $1*100 }'
  else
    echo "Brightness: $(xrandr --verbose |grep Brightness |grep -o '[0-9].*')"
    echo "Gamma: $(xrandr --verbose | grep Gamma | tr -d ' \t\n' |  awk -F: '{ printf "%f:%f:%f", 1/$2, 1/$3, 1/$4 }')"
  fi
else
  echo "up, down, gamma (r:g:b | night)"
fi
