#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --git-dir)"
trap 'rm -f "$dir/$$.tags"' EXIT
# vim ctags
git ls-files | \
    ctags --tag-relative=yes -L - -f "$dir/$$.tags"
mv "$dir/$$.tags" "$dir/tags"

# emacs etags
git ls-files | \
    ctags --tag-relative=yes -L - -f "$dir/$$.tags"
mv "$dir/$$.tags" "$dir/etags"
